// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjwb8jpNGLM3Gus0TtxSmQbXWrZUkoE8',
    appId: '1:154523249903:web:5f5a0143ee4b6d1c887f1a',
    messagingSenderId: '154523249903',
    projectId: 'lenk-chat',
    authDomain: 'lenk-chat.firebaseapp.com',
    storageBucket: 'lenk-chat.appspot.com',
    measurementId: 'G-ECSBTH0BBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsOEQeFdenFiVdD4S11hKw7Nf9i0hnGE',
    appId: '1:154523249903:android:6fb0a9363f0e4946887f1a',
    messagingSenderId: '154523249903',
    projectId: 'lenk-chat',
    storageBucket: 'lenk-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoaDtrID5IgZK3k-atj-077xa-0jy3sk',
    appId: '1:154523249903:ios:2af4e3d6f4a19d78887f1a',
    messagingSenderId: '154523249903',
    projectId: 'lenk-chat',
    storageBucket: 'lenk-chat.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoaDtrID5IgZK3k-atj-077xa-0jy3sk',
    appId: '1:154523249903:ios:dfc27e591ad295b2887f1a',
    messagingSenderId: '154523249903',
    projectId: 'lenk-chat',
    storageBucket: 'lenk-chat.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
